#!/usr/bin/env python3
"""SMT bulk numerical bounds for scientific catalog residual gates.

Role in the high-assurance pipeline (Lean master + SMT bulk + TLA+ flow):
  - Lean 4 owns definitions and large-scale structure.
  - Interactive provers (Coq/Isabelle/F*) re-check exported catalog lemmas.
  - SMT (Z3 / CVC5 when installed) is the automated muscle for continuous
    residual / margin inequalities over the catalog obligation set.

When z3/cvc5 are not on PATH, falls back to the same pure-Python decimal
checks used by the cross-proof runner (still records each obligation).
Also emits SMT-LIB2 for external bulk solvers under verification/smt/.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from decimal import Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from cross_proof_lib import python_verify_obligation  # noqa: E402
from tool_path_lib import find_cvc5, find_z3  # noqa: E402

OBL = ROOT / "verification" / "obligations" / "scientific_catalog_spine.json"
OUT_DIR = ROOT / "verification" / "smt"
REPORT = ROOT / "data" / "smt_catalog_bounds_report.json"
SMT2_BUNDLE = OUT_DIR / "scientific_catalog_bounds.smt2"


def _find_solver() -> tuple[str, str] | None:
    z3 = find_z3()
    if z3:
        return "z3", z3
    cvc5 = find_cvc5()
    if cvc5:
        return "cvc5", cvc5
    for name in ("z3", "z3.exe", "cvc5", "cvc5.exe"):
        p = shutil.which(name)
        if p:
            label = "z3" if "z3" in name.lower() else "cvc5"
            return label, p
    return None


def _smt_real(x: float) -> str:
    """SMT-LIB real literal without scientific notation (Z3 rejects 1e-12 as a token)."""
    if isinstance(x, bool):
        raise TypeError("bool is not a real")
    d = Decimal(str(x))
    # Fixed-point style: enough digits for residual gates; no exponent form.
    s = format(d, "f")
    if "." not in s:
        s = s + ".0"
    # Strip trailing zeros but keep at least one fractional digit
    if "." in s:
        whole, frac = s.split(".", 1)
        frac = frac.rstrip("0") or "0"
        s = f"{whole}.{frac}"
    return s


def _smt_atom(ob: dict, idx: int) -> str | None:
    """Encode one obligation as SMT-LIB2 assert (QF_LRA / QF_LIA)."""
    kind = ob["kind"]
    tag = f"o{idx}"
    if kind == "lt_half":
        v = _smt_real(float(ob["value"]))
        return f"(assert (! (< {v} 0.5) :named {tag}))"
    if kind == "lt_lit":
        v = _smt_real(float(ob["value"]))
        b = _smt_real(float(ob["bound"]))
        return f"(assert (! (< {v} {b}) :named {tag}))"
    if kind == "r_lt_lit_pure":
        l = _smt_real(float(ob["left_value"]))
        r = _smt_real(float(ob["right_value"]))
        return f"(assert (! (< {l} {r}) :named {tag}))"
    if kind == "abs_diff_lt_lit":
        d = _smt_real(float(ob["diff"]))
        b = _smt_real(float(ob["bound"]))
        return f"(assert (! (< {d} {b}) :named {tag}))"
    if kind == "pos":
        v = _smt_real(float(ob["value"]))
        return f"(assert (! (> {v} 0.0) :named {tag}))"
    if kind == "nat_pos":
        v = int(ob["value"])
        return f"(assert (! (> {v} 0) :named {tag}))"
    if kind == "eq_nat":
        l = int(ob["value"])
        r = int(ob.get("right_value", l))
        return f"(assert (! (= {l} {r}) :named {tag}))"
    return None


def write_smt2(obligations: list[dict]) -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "; FSOT scientific catalog residual / seed bounds — bulk SMT check",
        "; Generated by scripts/run_smt_catalog_bounds.py",
        "; Logic: QF_LIRA (reals + ints, no quantifiers)",
        "(set-logic QF_LIRA)",
        "(set-option :produce-unsat-cores true)",
    ]
    written = 0
    for i, ob in enumerate(obligations):
        atom = _smt_atom(ob, i)
        if atom:
            lines.append(f"; {ob['id']} kind={ob['kind']}")
            lines.append(atom)
            written += 1
    lines.append("(check-sat)")
    lines.append("(exit)")
    SMT2_BUNDLE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return written


def run_external_solver(solver_label: str, tool: str) -> dict:
    """Ask solver whether the conjunction of catalog bounds is SAT (should be)."""
    try:
        if solver_label == "z3":
            cmd = [tool, str(SMT2_BUNDLE)]
        else:
            # cvc5
            cmd = [tool, "--lang=smt2", str(SMT2_BUNDLE)]
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
        stdout = (r.stdout or "").strip()
        stderr = (r.stderr or "").strip()
        lines = [ln.strip().lower() for ln in stdout.splitlines() if ln.strip()]
        # Ignore (error ...) chatter; accept a clean trailing sat
        answers = [ln for ln in lines if ln in ("sat", "unsat", "unknown")]
        answer = answers[-1] if answers else ""
        has_error = "(error" in stdout.lower() or "(error" in stderr.lower()
        if answer == "sat" and not has_error and r.returncode == 0:
            status = "passed"
        elif answer == "unsat":
            status = "failed"
        elif answer == "sat" and has_error:
            status = "failed"
        else:
            status = "failed"
        return {
            "status": status,
            "answer": answer or "other",
            "returncode": r.returncode,
            "stdout_tail": (stdout + "\n" + stderr)[-800:],
        }
    except Exception as e:
        return {"status": "failed", "reason": str(e)}


def run_python_bulk(obligations: list[dict]) -> dict:
    failed: list[str] = []
    for ob in obligations:
        if not python_verify_obligation(ob):
            failed.append(ob["id"])
    return {
        "status": "passed" if not failed else "failed",
        "checked": len(obligations),
        "failed_ids": failed[:50],
        "failed_count": len(failed),
    }


def main() -> int:
    if not OBL.exists():
        print("MISSING scientific_catalog_spine.json — run export_scientific_catalog_obligations.py", file=sys.stderr)
        REPORT.write_text(
            json.dumps(
                {
                    "generated_at": datetime.now(timezone.utc).isoformat(),
                    "status": "missing_obligations",
                    "overall_ok": False,
                },
                indent=2,
            ),
            encoding="utf-8",
        )
        return 1

    doc = json.loads(OBL.read_text(encoding="utf-8"))
    obligations = doc.get("obligations") or []
    smt_written = write_smt2(obligations)
    py = run_python_bulk(obligations)

    solver = _find_solver()
    external: dict | None = None
    solver_name = "python_decimal_fallback"
    if solver:
        solver_name, tool = solver
        external = run_external_solver(solver_name, tool)

    # overall: Python must pass; external sat when present
    overall = py["status"] == "passed"
    if external is not None:
        overall = overall and external.get("status") == "passed"

    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "purpose": "SMT bulk numerical bounds on scientific catalog residual gates",
        "obligation_source": str(OBL.relative_to(ROOT)).replace("\\", "/"),
        "obligation_count": len(obligations),
        "domain_count": doc.get("domain_count"),
        "smt2_bundle": str(SMT2_BUNDLE.relative_to(ROOT)).replace("\\", "/"),
        "smt2_assert_count": smt_written,
        "solver": solver_name,
        "external_solver": external,
        "python_decimal": py,
        "checked": py["checked"],
        "status": "passed" if overall else "failed",
        "overall_ok": overall,
        "role": (
            "Bulk continuous residual / margin checks for the catalog atlas. "
            "Does not replace Lean master definitions or interactive multi-prover lemmas."
        ),
        "note": (
            "Install z3 or cvc5 on PATH for external SMT; otherwise python_decimal_fallback "
            "still machine-checks every exported catalog obligation."
        ),
    }
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(
        f"SMT catalog bounds: {report['status']} "
        f"(solver={solver_name}, checked={py['checked']}, smt2_asserts={smt_written})"
    )
    return 0 if overall else 1


if __name__ == "__main__":
    raise SystemExit(main())
