#!/usr/bin/env python3
"""Sync extension domain findings into the portable core formula fractal branch index."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None

ROOT = Path(__file__).resolve().parents[1]
SPINE_PATH = ROOT / "data" / "fsot_formula_spine.yaml"
MANIFEST_PATH = ROOT / "data" / "extension_domains_manifest.yaml"
OUT_JSON = ROOT / "data" / "core_formula_fractal_branch_index.json"
COMPUTE_PATH = ROOT / "vendor" / "fsot_compute.py"

MARKER_START = "# FSOT_EXTENSION_FRACTAL_BRANCHES_START"
MARKER_END = "# FSOT_EXTENSION_FRACTAL_BRANCHES_END"


def _load_yaml(path: Path) -> dict:
    if yaml is None or not path.is_file():
        return {}
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _lean_branch_for_tags(tags: list[str], observed: bool, recent_hits: int, d_eff: int) -> str:
    tags_set = set(tags or [])
    spine = _load_yaml(SPINE_PATH)
    branches = spine.get("branches") or {}
    if observed:
        return "term1.quirkMod"
    if recent_hits > 0:
        return "term1.growth_term"
    if d_eff >= 16:
        return "term3.chaos_factor"
    for _name, cfg in branches.items():
        if tags_set & set(cfg.get("lean_domains") or []):
            child = (cfg.get("children") or ["term1_base"])[0]
            return f"{_name}.{child}"
    return "term1.term1_base"


def _fractal_divergence(*, branch: str, n_tags: int, tier: int) -> float:
    depth = branch.count(".") + 1
    return round(depth + n_tags * 0.35 + tier * 0.25, 4)


def build_branch_index() -> dict:
    ext = _load_yaml(MANIFEST_PATH).get("extension_domains") or {}
    by_core: dict[str, list[dict]] = {}
    attachments: list[dict] = []
    for name, cfg in sorted(ext.items(), key=lambda x: (x[1].get("tier", 0), x[0])):
        tags = list(cfg.get("maps_to_lean") or [])
        branch = cfg.get("formula_branch_override") or _lean_branch_for_tags(
            tags,
            observed=bool(cfg.get("observed")),
            recent_hits=int(cfg.get("recent_hits") or 0),
            d_eff=int(cfg.get("D_eff") or 15),
        )
        div = _fractal_divergence(branch=branch, n_tags=len(tags), tier=int(cfg.get("tier") or 20))
        row = {
            "panel": name,
            "tier": cfg.get("tier"),
            "primary_branch": branch,
            "divergence_depth": div,
            "maps_to_lean": tags,
            "D_eff": cfg.get("D_eff"),
            "benchmark_data": cfg.get("benchmark_data"),
        }
        attachments.append(row)
        for tag in tags:
            by_core.setdefault(tag, []).append(row)
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "root": "raw_S",
        "core_domains": 35,
        "extension_panels": len(attachments),
        "attachments": attachments,
        "by_lean_tag": {k: v for k, v in sorted(by_core.items())},
    }


def _patch_spine(index: dict) -> None:
    if yaml is None or not SPINE_PATH.is_file():
        return
    spine = _load_yaml(SPINE_PATH)
    spine["updated"] = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    spine["extension_branch_index"] = {
        "panel_count": index["extension_panels"],
        "core_domain_count": index["core_domains"],
        "index_path": "data/core_formula_fractal_branch_index.json",
        "note": "All extension panels attach to raw_S fractal branches without domain-specific fitting.",
    }
    SPINE_PATH.write_text(yaml.dump(spine, sort_keys=False, default_flow_style=False), encoding="utf-8")


def _patch_compute(index: dict) -> None:
    if not COMPUTE_PATH.is_file():
        return
    text = COMPUTE_PATH.read_text(encoding="utf-8")
    block_lines = [
        MARKER_START,
        "# Auto-generated by scripts/sync_core_formula_fractal_branches.py — do not edit by hand.",
        f"EXTENSION_FRACTAL_PANEL_COUNT = {index['extension_panels']}",
        "EXTENSION_FRACTAL_BRANCHES: dict[str, str] = {",
    ]
    for row in index["attachments"]:
        panel = row["panel"]
        branch = row["primary_branch"]
        block_lines.append(f'    "{panel}": "{branch}",')
    block_lines.append("}")
    block_lines.append("")
    block_lines.append("def extension_branch_for_panel(panel: str) -> str:")
    block_lines.append('    """Return fractal spine branch for an extension panel name."""')
    block_lines.append("    return EXTENSION_FRACTAL_BRANCHES.get(panel, \"term1.term1_base\")")
    block_lines.append(MARKER_END)
    block = "\n".join(block_lines)

    if MARKER_START in text and MARKER_END in text:
        pre = text.split(MARKER_START)[0].rstrip()
        post = text.split(MARKER_END)[1].lstrip("\n")
        text = pre + "\n\n" + block + "\n" + post
    else:
        anchor = "DOMAINS = _build_domains()"
        if anchor not in text:
            return
        text = text.replace(anchor, block + "\n\n\n" + anchor)
    COMPUTE_PATH.write_text(text, encoding="utf-8")


def main() -> int:
    index = build_branch_index()
    OUT_JSON.write_text(json.dumps(index, indent=2), encoding="utf-8")
    _patch_spine(index)
    _patch_compute(index)
    print(
        f"Synced {index['extension_panels']} extension panels into core formula fractal index "
        f"({OUT_JSON.name}, {SPINE_PATH.name}, {COMPUTE_PATH.name})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())